# Generated by Django 5.2.8 on 2025-11-10 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='companion_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
