# Generated by Django 5.2.8 on 2025-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Home City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Home State/Region'),
        ),
    ]
