"""
Django settings for senior_companion_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# --- ADD THIS LINE ---
ASGI_APPLICATION = 'senior_companion_project.asgi.application'
# --- END OF ADDED LINE ---
import os
from pathlib import Path
import os # Make sure this is at the top
from pathlib import Path # Make sure this is at the top
import os
from dotenv import load_dotenv
    
    # This line reads your .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lh%k)l@m3q8-m)xfuelga$sadlyr5!w*g5enxc06%8k!y10hae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Our new apps ---
    # We must register all our apps here
    'users.apps.UsersConfig', # We use .apps.UsersConfig for our signal
    'resources.apps.ResourcesConfig',
    
    'channels',
    'chat.apps.ChatConfig',
    # --- ADD THESE TWO NEW APPS ---
    'reminders.apps.RemindersConfig',
    'django_celery_beat',
    'django.contrib.humanize', # <-- ADD THIS LINE
    # --- ADD THIS LINE ---
    'chatbot',

    # --- END OF NEW APPS ---
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'senior_companion_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'senior_companion_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'senior_companion_db',     # The name you chose in Step 2
        'USER': 'postgres',                 # The default superuser
        'PASSWORD': 'postgres',             # The password you set in Step 1
        'HOST': '127.0.0.1',                # 'localhost'
        'PORT': '5432',                     # The default port
    }
} 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# --- Custom User Model ---
# This is CRITICAL. We're telling Django
# to use OUR CustomUser model for authentication.
AUTH_USER_MODEL = 'users.CustomUser'

# Where to redirect users *after* they log in
LOGIN_REDIRECT_URL = 'home'

# Where to redirect users *after* they log out
LOGOUT_REDIRECT_URL = 'home'


# --- CHANNELS CONFIGURATION ---
# This tells Django to use Channels as the main web server (ASGI)
ASGI_APPLICATION = 'senior_companion_project.asgi.application'

# This configures the "Channel Layer" to use Redis
# It will connect to the redis-server you have running.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6380)],
        },
    },
}


# --- Celery Configuration ---
# We're using our existing Redis server, which is great!
CELERY_BROKER_URL = 'redis://127.0.0.1:6380/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6380/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' # Use UTC to avoid timezone issues

# --- Celery Beat (Scheduler) Configuration ---
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# --- EMAIL CONFIGURATION (For Development) ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'reminders@senior-companion.com'


# --- EMAIL CONFIGURATION (For Production with Gmail) ---
    
    # Use 'smtp' for real emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    
    # Gmail's Server
EMAIL_HOST = 'smtp.gmail.com'
    
    # Gmail's Port
EMAIL_PORT = 587
    
    # Use TLS (for security)
EMAIL_USE_TLS = True
    
    # Read the username and password from your secret .env file
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
    
    # Set the default "From" address for your emails
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_USER')

# --- MEDIA FILES (User Uploaded Content) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'