# Generated by Django 5.2.8 on 2025-12-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text="The keyword or phrase to look for (e.g., 'register', 'password')", max_length=255)),
                ('match_type', models.CharField(choices=[('contains', 'Contains Keyword'), ('exact', 'Exact Match'), ('regex', 'Regular Expression (Advanced)')], default='contains', max_length=20)),
                ('response', models.TextField(help_text='The answer to give.')),
                ('suggested_link', models.CharField(blank=True, help_text="Optional: URL path to redirect user (e.g., '/accounts/login/')", max_length=200, null=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers are checked first.')),
            ],
        ),
        migrations.CreateModel(
            name='UnansweredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
