# Generated by Django 5.2.8 on 2025-11-09 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='policy_link',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='content',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='external_link',
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_type',
            field=models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('home', 'Home Insurance'), ('other', 'Other')], default='health', max_length=10),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='provider_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningresource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('guide', 'Guide'), ('other', 'Other')], default='article', max_length=10),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='users.hobby'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='category',
            field=models.CharField(choices=[('park', 'Park'), ('museum', 'Museum'), ('club', 'Community Club'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.hobby')),
            ],
        ),
    ]
