# Generated by Django 5.2.8 on 2025-11-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_insurancepolicy_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Place Categories',
            },
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='has_restrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='has_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.placecategory'),
        ),
    ]
