# Generated by Django 5.2.8 on 2025-11-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_placecategory_placetovisit_has_restrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/main/'),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='resources.placetovisit')),
            ],
        ),
    ]
