# Generated by Django 5.2.8 on 2025-11-18 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_placetovisit_main_image_placeimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='coverage_summary',
            field=models.TextField(blank=True, help_text='A simple, non-technical summary of coverage.'),
        ),
        migrations.CreateModel(
            name='UserInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('coverage_type', models.CharField(choices=[('health', 'Health'), ('life', 'Life'), ('auto', 'Auto'), ('home', 'Home/Renters'), ('travel', 'Travel'), ('other', 'Other')], default='health', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one-time', 'One-Time')], default='monthly', max_length=10)),
                ('policy_document', models.FileField(blank=True, help_text='Upload a scanned copy of your policy (PDF, JPG, etc.)', null=True, upload_to='policies/documents/')),
                ('coverage_summary', models.TextField(blank=True, help_text='Your personal notes or summary of coverage.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
