# Generated by Django 5.2.8 on 2025-11-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_insurancepolicy_coverage_summary_userinsurancepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_geriatrics_dept',
            field=models.BooleanField(default=False, verbose_name='Has Geriatrics Department'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_emergency_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(choices=[('cardio', 'Cardiology'), ('geriatrics', 'Geriatrics'), ('ortho', 'Orthopedics'), ('opthal', 'Ophthalmology'), ('dental', 'Dentistry'), ('gp', 'General Practitioner'), ('neuro', 'Neurology')], max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('years_experience', models.IntegerField(default=5)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated list (e.g., Hindi, English)', max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/profiles/')),
                ('visiting_hours', models.TextField(blank=True, help_text='e.g., Mon, Wed, Fri: 10 AM - 2 PM')),
                ('hospital_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_doctors', to='resources.hospital')),
            ],
        ),
    ]
