# Generated by Django 5.2.8 on 2025-11-25 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_hospital_has_elevator_hospital_has_geriatrics_dept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner (Easy)'), ('intermediate', 'Intermediate (Moderate)'), ('advanced', 'Advanced (Challenging)')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link for videos or external articles (e.g., YouTube URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Upload a PDF or document', null=True, upload_to='learning/files/'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article / Guide'), ('video', 'Video'), ('pdf', 'Downloadable PDF'), ('tutorial', 'Interactive Tutorial')], default='article', max_length=10),
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('bookmarked', 'Bookmarked')], default='not_started', max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Progress Records',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
