# Generated by Django 5.2.8 on 2025-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_game_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('puzzle', 'Puzzle/Memory'), ('board', 'Board Game'), ('word', 'Word Game')], default='puzzle', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.CharField(default='', help_text='The URL path where the game is located (e.g., /games/memory/)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_high_contrast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_large_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_multiplayer_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
